# Generated by Django 3.2.5 on 2021-09-12 23:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ImageColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MuseumObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_identifier', models.CharField(default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=5000)),
                ('collection', models.ManyToManyField(to='inventory.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectLocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('museum_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.museumobject')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(default='', max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.objectlocationtype')),
                ('museum_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.museumobject')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('color', models.ManyToManyField(to='inventory.ImageColor')),
                ('museum_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.museumobject')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=80)),
                ('museum_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.museumobject')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.objectdatetype')),
            ],
        ),
        migrations.AddField(
            model_name='museumobject',
            name='creator',
            field=models.ManyToManyField(blank=True, to='inventory.ObjectCreator'),
        ),
        migrations.AddField(
            model_name='museumobject',
            name='language',
            field=models.ManyToManyField(to='inventory.LanguageCode'),
        ),
        migrations.AddField(
            model_name='museumobject',
            name='publisher',
            field=models.ManyToManyField(to='inventory.ObjectPublisher'),
        ),
        migrations.AddField(
            model_name='museumobject',
            name='subject',
            field=models.ManyToManyField(blank=True, to='inventory.ObjectSubject'),
        ),
        migrations.AddField(
            model_name='collection',
            name='domain',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.collectiondomain'),
        ),
        migrations.AddField(
            model_name='collection',
            name='museum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.museum'),
        ),
    ]
